import { inject, Injectable } from '@angular/core';
import { ApiService } from 'projects/tenant-numany/src/app/core/services/api.service';
import { Observable } from 'rxjs';

// This is the core data structure for an alert message from the API.
export interface AlertMessage {
  id: number; // Use string if your API uses UUIDs, etc.
  msg_name: string;
  msg_txt: string;
}

export interface AlertMessageUpdateResponse {
  isUpdated: boolean;
  message: string;
}

// This is the payload used when CREATING or UPDATING a message.
// The 'id' is omitted because it's generated by the server on creation.
export type AlertMessagePayload = Omit<AlertMessage, 'id'>;

// This represents the typical API response when fetching a list of messages.
// APIs often wrap arrays in an object for metadata (e.g., count, pagination).
export interface AlertMessagesResponse {
  data: AlertMessage[];
  count: number;
}

// A generic success response for DELETE operations.
export interface DeleteResponse {
  isDeleted: boolean;
  message: string;
}

@Injectable()
export class TenantAlertMessageService {
  private apiService = inject(ApiService);

  // Endpoint base path
  private readonly endpointUrl = '/AlertMessage';

  /**
   * Fetches all tenant alert messages.
   */
  getTenantAlertMessages(): Observable<AlertMessagesResponse> {
    return this.apiService.get<AlertMessagesResponse>(this.endpointUrl);
  }

  /**
   * Creates a new tenant alert message.
   * @param payload The message data to create.
   */
  createTenantAlertMessage(payload: AlertMessagePayload): Observable<AlertMessage> {
    // A POST request to the base URL typically creates a new resource.
    // The API should return the newly created message, including its ID.
    return this.apiService.post<AlertMessage>(this.endpointUrl, payload);
  }

  /**
   * Updates an existing tenant alert message.
   * @param id The ID of the message to update.
   * @param payload The new message data.
   */
  updateTenantAlertMessage(
    id: number,
    payload: AlertMessagePayload,
  ): Observable<AlertMessageUpdateResponse> {
    // A PUT or PATCH request to a specific resource URL updates it.
    return this.apiService.put<AlertMessageUpdateResponse>(`${this.endpointUrl}/${id}`, {
      alertMessage: payload,
    });
  }

  /**
   * Deletes a tenant alert message.
   * @param id The ID of the message to delete.
   */
  deleteTenantAlertMessage(id: number): Observable<DeleteResponse> {
    return this.apiService.delete<DeleteResponse>(`${this.endpointUrl}/${id}`);
  }
}
